### PR TITLE
Create b-musick.md

### PR DESCRIPTION
**Pull request by B-Musick**

### CODE REVIEW

**Comment by LukeSchlangen** [comment]
Hi @B-Musick! This is a great start! A few suggestions before I merge:

1. Could you change the title to your name/username (something other than testing)?
2. Could you add some detail below to practice markdown outside of the heading?
3. If you add a space between the `#` and the first letter in your heading, it will format more nicely.

If you do those things, I'd be happy to merge!

**Comment by B-Musick** [comment]
Sorry about that. Thanks for the tutorials they are really helpful!

**Comment by LukeSchlangen** [comment]
No worries. Glad you like them!

Approved! congrats on your first open source contribution! Welcome!

**Comment by B-Musick** [comment]
Thanks a lot! I appreciate the feedback!

**Pull request merged**
